### ISSUE TITLE
Replace ifconfig with equivalent ip command

### ISSUE THREAD

**Issue by peterglock** [ogra1/mac-spoofer-snap#1]
Later versions of linux don't have ifconfig and other network tools installed by default. Consider using:

```
ip link set eth0 down
ip link set dev eth0 address 00:0c:29:33:4e:aa
ip link set eth0 up
```

**Comment by ogra1** [comment]
Ha ! Thanks a lot for the heads up, I have not touched that code since 2016 (where ifconfig was still around) and had totally forgotten about it ... this is fixed now
